export const ROUTES = {
  HOME: '/',
  FEATURES: '/features',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  WORKSPACES: '/workspaces',
  MEETINGS: '/meetings',
  RECORDINGS: '/recordings',
  TRANSCRIPTS: '/transcripts',
  SUMMARIES: '/summaries',
  ACTION_ITEMS: '/action-items',
  SEARCH: '/search',
  NOTIFICATIONS: '/notifications',
  ANALYTICS: '/analytics',
  AUDIT_LOGS: '/audit-logs',
  ADMIN: '/admin',
} as const
